### ISSUE TITLE
Add finishing touches for v0.1

### ISSUE THREAD

**Issue by abhi18av** [Aryan-sharma11/AddSevenPS#1]
- [x] Documentation (for usage of powershell library)
- [x] Add code comments and reformat the code
- [x] Release `v0.1` 
- [x] Work on a `develop` branch and create a PR
- [x] Invite @abhi18av to the repo
- [x] Improve folder structure
- [x] Add tests

**Comment by Aryan-sharma11** [comment]
We have also progressed until v0.2 https://github.com/Aryan-sharma11/AddSevenPS/releases/tag/v0.2
