### ISSUE TITLE
.NET framework to .NET/.NET core

### ISSUE THREAD

**Issue by Aryan-sharma11** [Aryan-sharma11/AddSevenPS#2]
I accidentally selected  .net framework  while creating a new Class Library , so is there a way to port from .NET framework to  .NET core ?

**Comment by abhi18av** [comment]
This you'll need to discover using the IDE settings :)

**Comment by abhi18av** [comment]
@Aryan-sharma11 , did this get resolve via the IDE?

**Comment by Aryan-sharma11** [comment]
> @Aryan-sharma11 , did this get resolve via the IDE?

not yet .. although there were some articles about using  " .NET portability analyzer"  in visual studio

**Comment by abhi18av** [comment]
@Aryan-sharma11 , think simple.

This is a small project - in the worst case, you can recreate a project and do a `force-push` on this repo.
